---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: project
    component: bot
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
      component: bot
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: project
        component: bot
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: bot
        env:
        - name: MONGO
          value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
          value: "27017"
        - name: RMQ_HOST
          value: {{ .Values.rabbitmqHost | default (printf "%s-rabbitmq" .Release.Name) }}
        - name: RMQ_QUEUE
          value: queue1
        - name: RMQ_USERNAME
          value: {{ .Values.user }}
        - name: RMQ_PASSWORD
          value: {{ .Values.password }}
        - name: CHECK_INTERVAL
          value: "60"
        - name: EXCLUDE_URLS
          value: .*github.com
