---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  labels:
    app: crawler
    component: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: mongodb-exporter
  template:
    metadata:
      name: mongodb-exporter
      labels:
        app: crawler
        component: mongodb-exporter
    spec:
      containers:
      - image: bitnami/mongodb-exporter
        name: mongodb-exporter
        env:
        - name: MONGODB_URL
          value: mongodb
