---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    component: rabbitmq
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.externalPort }}
  selector:
    component: rabbitmq
    release: {{ .Release.Name }}